export const BRAND_GUIDELINES = {
  stripe: 'https://stripe.com/docs/brand',
  figma: 'https://www.figma.com/brand',
  linear: 'https://linear.app',
  vercel: 'https://vercel.com/design',
  supabase: 'https://supabase.com/brand-assets',
  github: 'https://github.com',
  notion: 'https://notion.so',
  airbnb: 'https://airbnb.design',
  spotify: 'https://developer.spotify.com/documentation/design',
  slack: 'https://slack.com/brand-guidelines',
  discord: 'https://discord.com/branding',
  tailwind: 'https://tailwindcss.com',
  nextjs: 'https://nextjs.org',
  react: 'https://react.dev',
  shadcn: 'https://ui.shadcn.com',
  radix: 'https://www.radix-ui.com',
  shopify: 'https://www.shopify.com/brand-assets',
  apple: 'https://developer.apple.com/design',
  google: 'https://design.google',
  microsoft: 'https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks',
  meta: 'https://about.meta.com/brand/resources/meta/company-brand',
  netflix: 'https://brand.netflix.com',
  uber: 'https://brand.uber.com',
  twitter: 'https://about.twitter.com/en/who-we-are/brand-toolkit',
  linkedin: 'https://brand.linkedin.com',
}

export const SUGGESTED_BRANDS = ['stripe', 'linear', 'figma', 'supabase', 'airbnb', 'spotify']
